# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_cFaBo5-DbXbJMJ6MIBohFtWW-o956Q
"""

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# from sklearn.preprocessing import LabelEncoder
# from sklearn.ensemble import RandomForestRegressor
# 
# st.title("🌾 Crop Yield Prediction System")
# 
# st.write("Enter values to predict crop yield")
# 
# # Load dataset (upload your CSV in Colab first)
# df = pd.read_csv("indiancrop_dataset.csv")
# 
# df = df.dropna()
# 
# # Encode categorical columns
# le = LabelEncoder()
# for col in df.columns:
#     if df[col].dtype == 'object':
#         df[col] = le.fit_transform(df[col])
# 
# # Detect target column
# if 'Production' in df.columns:
#     target = 'Production'
# elif 'Yield' in df.columns:
#     target = 'Yield'
# else:
#     target = df.columns[-1]
# 
# X = df.drop(target, axis=1)
# y = df[target]
# 
# # Train model
# model = RandomForestRegressor(n_estimators=100)
# model.fit(X, y)
# 
# st.subheader("Enter Input Features")
# 
# input_data = []
# 
# for col in X.columns:
#     val = st.number_input(f"{col}", value=0.0)
#     input_data.append(val)
# 
# input_array = np.array(input_data).reshape(1, -1)
# 
# if st.button("Predict"):
#     prediction = model.predict(input_array)
#     st.success(f"🌾 Predicted Crop Yield: {prediction[0]:.2f}")

import pandas as pd
df = pd.read_csv("/content/indiancrop_dataset.csv")

from pyngrok import ngrok

ngrok.set_auth_token("3D810suXB5zMGtuk9n6h81fv0oK_2kWjoq2esjpLSdHeoATB1")
# Kill old connections
ngrok.kill()

# Run streamlit in background
get_ipython().system_raw('streamlit run app.py &')

# Open tunnel
public_url = ngrok.connect(8501)
print(public_url)